### ISSUE TITLE
Add Banner to SharePoint Online Classic page solution

### ISSUE THREAD

**Issue by troytmartin** [bschlintz/spfx-message-banner#11]
Hello,
The banner works great on modern pages, however, does not work on SharePoint online Classic pages.  Many site admins, are looking for solutions where classic pages were migrated over to SPO, however, they are stale, and admins want to add a banner to notify them, the site will be deactivated if the site is not used.

Thanks for your time!

Troy

**Comment by bschlintz** [comment]
Hi @troytmartin, SPFx-based solutions will not work on classic pages. For that you could explore custom actions with JavaScript injection which was the old way of doing this on classic sites before SPFx existed. Alternatively, a custom masterpage could be a short-term solution.
