### ISSUE TITLE
SharePoint SE On-Prem

### ISSUE THREAD

**Issue by s31064** [bschlintz/spfx-message-banner#12]
Is there a way to make this work for SharePoint SE on-prem?  We've been using banners for years (thanks to Saludeen @ SharePointDiary.com), but since we upgraded to SE, that method doesn't work.

**Comment by bschlintz** [comment]
UPDATED: @s31064, I think 2019/SE are at SPFx v1.4.1, but most or all of the functionality in this project _should_ be compatible with that older version. However, you will need to backport the code to the older SPFx version in a new project. Deploying this solution as-is likely will not work in 2019/SE.

**Comment by s31064** [comment]
@bschlintz If I actually put my mind to it and learned the underlying code I'm sure I could port it, but I just don't have the time.  Between working an average of 10 hours a day, four grandkids that all play multiple sports year-round, and the fact that I do take some time out almost every day to eat and sleep, the time to learn never seems to materialize.  ;-)

**Comment by bschlintz** [comment]
@s31064 Ha! Yes, I totally understand the pesky limitation of 24-hour days. It's a tricky problem. :)

This project has fallen to the back burner, and I don't have extra hours to dedicate to it. If you're able to find the time, or find someone who does, I'd be happy to accept a PR for a 2019/SE-compatible branch.

All the best!
