### ISSUE TITLE
Page title hidden with banner

### ISSUE THREAD

**Issue by arjohnson77** [bschlintz/spfx-message-banner#4]
This banner worked for my needs, but after installing, when creating a new page the "Title" area is hidden and I am unable to save any new pages. 

![image](https://user-images.githubusercontent.com/11206370/84422342-bfa50900-abd1-11ea-8131-68c73352ddbc.png)

**Comment by bschlintz** [comment]
Typically the page title area is never shown on modern **home** pages by default. Non-home pages will have the page title area. You can modify the page layout type using the [PnP PowerShell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps) cmdlet [Set-PnPClientSidePage](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpclientsidepage?view=sharepoint-ps).
