### ISSUE TITLE
Banner does not appear on Classic Team Site Home page

### ISSUE THREAD

**Issue by vishwasdm** [bschlintz/spfx-message-banner#5]
Hi,

this is really cool, I was looking for this banner update thing on SPO site for long time. thank you so much!!..

 I tried to apply banner text message on Classic SPO site but it does not appear on Classic SPO (STS#0) site home page and appears on rest of the site pages. please find attached pics. I did not find any issues with Teams associated sites. 
![bannerUpdate](https://user-images.githubusercontent.com/25613798/106187586-d5e8ef00-61cb-11eb-8c81-1eb1e725af58.JPG)
![bannerUpdate2](https://user-images.githubusercontent.com/25613798/106187702-f7e27180-61cb-11eb-8827-41582644cf81.JPG)

**Comment by bschlintz** [comment]
Hi @vishwasdm, I'm so glad you found the solution useful!

This banner is developed using SharePoint Framework (SPFx) and uses the [Application Customizer Extension](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/overview-extensions) which is not supported in SharePoint classic experiences. To make something similar in classic, I would recommend creating a custom action and leverage JavaScript injection. Bob German wrote an excellent blog post that I recommend which describes an approach to optimize code reuse for these scenarios: [Building Headers and Footers that work on Classic and Modern sites](https://bob1german.com/2018/03/11/building-headers-and-footers-that-work-on-classic-and-modern-sites/).

**Comment by RavindraEnakollu** [comment]
We have deployed the GitHub Banner solution without any issue and we are able to see the banner when we open the site but it is getting disappear after few seconds.

Could you please confirm which ClientSideComponentId we have to use in pnp powershell while configuration.
We have used the same as given in example. Is that correct id?
ClientSideComponentId "1e2688c4-99d8-4897-8871-a9c151ccfc87"


Please help us in resolving automatic disappearing of banner notification.
