### ISSUE TITLE
Can this be used in production environment?

### ISSUE THREAD

**Issue by flowrex** [bschlintz/spfx-message-banner#6]
Can this be used in a production environment and will it stay compatible with newer versions of SPfx?

Thanks

**Comment by bschlintz** [comment]
The project uses v1.9.1 of SPFx and hasn't been updated in a couple years. This is a production-ready solution but is a bit out of date now. I'd recommend forking the repo and upgrading to the latest version of SPFx, but the solution should work as-is in environments that support at least 1.9.1.
