### ISSUE TITLE
Activating on all Site Collections in the Tenant

### ISSUE THREAD

**Issue by srfdggy5** [bschlintz/spfx-message-banner#9]
Hey guys... I had a quick question re: how to activate this solution to all site collections in our tenant.

When I connect to PnPOnline, it obviously asked me for a URL. If I put in a specific site collection URL, and connect, then run the Add-PnPCustomAction for the banner, with -Scope Site, it works perfectly.

My assumption was, if I changed my connection to either the "https://mycompany-admin.sharepoint.com" or even just the root home site, and used -Scope Web, it would activate this for all site collections, but that isn't happening. Is there a way to do this possibly?

When added to the app catalog, it was made available to all sites.

Thanks for any guidance at all guys!!

**Comment by azureskydiver** [comment]
I think you want `-Scope All` instead of `-Scope Web`.

**Comment by srfdggy5** [comment]
Thank you for the reply. I thought the same thing, but for this particular cmdlet, All is not an accepted value, just Site and Web. Ideas? Thanks again for the reply however!!!

**Comment by bschlintz** [comment]
Hi @srfdggy5, you could use [Tenant Wide Extensions](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/tenant-wide-deployment-extensions) to configure this solution for all sites. I have another project called [External Sharing Banner](https://github.com/bschlintz/spfx-external-sharing-banner) which does this if you want to take a look at how that one works. Going down the tenant wide extensions route will set the same message/settings for every site without the ability to customize on a per-site basis, which was the original design for this project. Alternatively, you could write a PowerShell script to configure this banner on as many sites as needed.

**Comment by srfdggy5** [comment]
Thanks for the information rad… Much appreciated.

 

So my initial understanding was that if I enabled the skipFeatureDeployment attribute (set to true), that would accomplish what I was looking for, in conjunction with setting the -Scope to Web.

 

I think I may still be missing something however.

**Comment by MamaDragon** [comment]
Thank you for this banner code it is great. I have a similar need to add banners across all site collection in the tenant and all pages.  how do we change the location of the banner to be the very first object on the page?   we will also need to have this same information at the bottom as well. 

Thanks!

**Comment by bschlintz** [comment]
Hello @MamaDragon, SPFx extensions can only be displayed in the defined placeholders supported by SharePoint Framework. The last I checked, the placeholders were `Top` (which this solution uses) and `Bottom`. I know this reply is late, but if you still need help, please open a new issue.
